### PR TITLE
Fix getChangedFiles of `GitClient`

### PR DESCRIPTION
**Pull request by mithem**
## Summary

Fix the way the git status command is parsed from CLI so that the changed files get parsed correctly.

## Changes Made

Move from string splitting to regex matching and tolerate both 1 or 2 spaces between git file mode and file name: It now tolerates both the format "M myfile.txt" as well as "A  new.swift" (git seems to use 2 spaces on my machine, but the system now also tolerates 1 (as I don't know if it worked with one space on another machine before)).

## TODO

None.

## Motivation

Make the correct file names appear in source control changes view (often included directories and many anomalies)

## Testing

Look at the changes view in a test repo

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [X] Code has been tested and verified.
- [ ] Documentation has been updated to reflect the changes.
- [X] All tests pass successfully.
- [X] Code follows the project's coding guidelines and style.
- [X] The branch is up-to-date with the latest changes from the main branch.
- [ ] Reviewed by at least one other contributor.

## Related Issues

This PR addresses the following issue(s): None.

### CODE REVIEW

**Comment by nanashili** [comment]
@0xWDG How does this look, to me it looks fine but not to sure with the regex and splitting

**Comment by 0xWDG** [comment]
It does look good to me, but the guard statements can be merged into one guard since they both throw the exact same error.

**Comment by nanashili** [comment]
> It does look good to me, but the guard statements can be merged into one guard since they both throw the exact same error.

Good catch!

**Comment by 0xWDG** [comment]
@nanashili Should we bump to MacOS 13?
We're now targeting 12

image

**Comment by nanashili** [comment]
This PR is being closed for the following reason stated below:

Due to the macOS target being increased and we don't plan on increasing it soon due to low requirements of macOS v13 features, this PR is considered not merge worthy at this point in time.

If the PR can make use of the current macOS build version then this PR will be reconsidered.

**Comment by mithem** [comment]
Alright, sorry for requiring that newer version. As a heads-up, it seems you at some point overwrote the minimum deployment target on the development branch (14.0), with 12.3 still on the main branch (that's why I didn't notice it). I think it would be helpful (also for other contributors) to update the development branch :)

**Comment by nanashili** [comment]
> Alright, sorry for requiring that newer version. As a heads-up, it seems you at some point overwrote the minimum deployment target on the development branch (14.0), with 12.3 still on the main branch (that's why I didn't notice it). I think it would be helpful (also for other contributors) to update the development branch :)

Do you perhaps know which commit caused this? Because from my knowledge we haven't switched to it yet we looked at it but there was no reason as of yet to upgrade.

**Comment by mithem** [comment]
> > Alright, sorry for requiring that newer version. As a heads-up, it seems you at some point overwrote the minimum deployment target on the development branch (14.0), with 12.3 still on the main branch (that's why I didn't notice it). I think it would be helpful (also for other contributors) to update the development branch :)
> 
> Do you perhaps know which commit caused this? Because from my knowledge we haven't switched to it yet we looked at it but there was no reason as of yet to upgrade.

It looks to me like 5d6e35f caused it.

**Pull request closed without merging**
