### PR TITLE
Added Deprecation Notices for Version Control System Remote Calls

### PR DESCRIPTION
**Pull request by nanashili**
This pull request introduces deprecation notices to the current remote calls within the version control system of the editor. The changes are necessary as we transition to using the standalone [Version Control Kit](https://github.com/AuroraEditor/Version-Control-Kit). The existing remote call system is outdated and lacks the performance optimizations required for modern usage, warranting a complete rewrite.

## Details:

* Deprecation Notices:
   * Added deprecation annotations to all functions and classes involved in remote calls within the current version control system.
   * Provided clear messages indicating the move to the new Version Control Kit and the upcoming changes.
   
* Transition Plan:
  * All remote calls will be moved to the new Version Control Kit repository.
  * The current system for remote calls will remain in place temporarily to ensure the editor remains fully functional during the transition period.

* Rationale:
  * The existing system is not performant and does not meet the current standards for remote operations.
  * The new Version Control Kit offers a more robust and efficient framework for handling version control operations.
  * The transition to the new kit will improve overall performance, maintainability, and future scalability of the editor.

* Next Steps:
  - Complete the rewrite of the remote call system within the Version Control Kit.
  - Gradually phase out the deprecated calls from the editor once the new system is fully integrated and tested.
  - Provide documentation and support to assist developers in adapting to the new system.

## Impact:

1. Users and developers will see deprecation warnings indicating the upcoming changes.
2. Existing functionality will remain unaffected until the new system is fully operational.
3. A smoother transition is ensured, minimizing disruptions to the editor’s use.

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Review by 0xWDG — DISMISSED** [review]

**Comment by 0xWDG** [comment]
@aurora-care-bear please approve.

**Review by aurora-care-bear — APPROVED** [review]
Approved on behalf of @0xWDG

**Comment by aurora-care-bear** [comment]
Hey @nanashili,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Pull request merged**
