### PR TITLE
Make inspector items same size, fixes #115

### LINKED ISSUE #115: [Inspector] different text sizes.
### Description

[Inspector] different text sizes.

image

### To Reproduce

^

### Expected behavior

Same sizes.

### Version information

Aurora Editor: 1.0 (1)
Commit: d06fb30e72634048395b5dbcdbc756b7f8ecc2f0
MacOS: 13.0 (22A5321d)
Xcode: 14.0 (14A5270f)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wdg**
Make inspector items same size

# Related Issue

#115

# Checklist

- [x] I read and understood the [contributing guide](https://github.com/AuroraEditor/AuroraEditor/blob/main/CONTRIBUTING.md) as well as the [code of conduct](https://github.com/AuroraEditor/AuroraEditor/blob/main/CODE_OF_CONDUCT.md)
- [x] My changes generate no new warnings
- [x] My code builds and runs on my machine
- [x] I documented my code
- [x] Review requested

# Screenshots

image

### CODE REVIEW

**Comment by nanashili** [comment]
Nope to big now

**Comment by wdg** [comment]
what size should become then?

**Comment by nanashili** [comment]
> what size should become then?

It should be 11, the menu sizes need to change

**Comment by nanashili** [comment]
the sizes it was, was correct the menu needs a custom view

**Comment by wdg** [comment]
The dropdown ignores sizes. (Less then 12)
It either should be written in UIKit or we must go with 12.

**Comment by nanashili** [comment]
> The dropdown ignores sizes. (Less then 12)
> It either should be written in UIKit or we must go with 12.

The drop down is not a problem, it's more the main view of it

**Pull request closed without merging**
