### PR TITLE
Improved about screen

### PR DESCRIPTION
**Pull request by nanashili**
## Changes Made
Refactor: Eliminated repetitive code in the `loadCredits` and `loadLicense` functions by creating a generic function to read the contents of a file, improving code maintainability and reducing redundancy.

Extracted window configuration to a configureWindow method for improved readability.

Introduced a setupEscapeKeyEventHandler method to centralize event monitor setup.

Created an animateWindow method to handle window animations, reducing code duplication.

Added a removeEscapeKeyEventHandler method to ensure the event monitor is removed during deinitialization.

Added a required init?(coder:) method to conform to NSWindowController subclass requirements, even though it throws an error because the class is not intended to be initialized from a coder.

Added support for cache images and improved handling of about states, enhancing the user experience and visual presentation.

## TODO
NONE

## Motivation
The user experience with the About screen was not very performant and the constant image loading was not ideal

## Testing
Opened and closed multiple times

## Screenshots/GIFs
NONE

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [X] Code has been tested and verified.
- [X] Documentation has been updated to reflect the changes.
- [X] All tests pass successfully.
- [X] Code follows the project's coding guidelines and style.
- [X] The branch is up-to-date with the latest changes from the main branch.

## Related Issues

This PR addresses the following issue(s): NONE

## Additional Notes
NONE

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Review by 0xWDG — APPROVED** [review]

**Comment by 0xWDG** [comment]
@aurora-care-bear please approve this PR

**Review by aurora-care-bear — APPROVED** [review]
Approved on behalf of @0xWDG

**Comment by aurora-care-bear** [comment]
Hey @nanashili,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Pull request merged**
