### PR TITLE
delete item to trash

### PR DESCRIPTION
**Pull request by 0xWDG**
## Summary

delete item to trash instead of deleting it directly, this takes care that a user which deletes their files unintended can get it back using the "Trash".

## Changes Made

Move to trash instead of delete.

## TODO

None.

## Motivation

this takes care that a user which deletes their files unintended can get it back using the "Trash".

## Testing

None

## Screenshots/GIFs

image

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [x] Code has been tested and verified.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.
- [x] Reviewed by at least one other contributor.

## Related Issues

This PR addresses the following issue(s): None

## Additional Notes

None

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Comment by nanashili** [comment]
Maybe give the user an option? Delete permanently or move to trash?

**Comment by 0xWDG** [comment]
> Maybe give the user an option? Delete permanently or move to trash?

This is what Xcode does as well, and might be the safest option.

We can make ⌘ Delete for permanent delete, but I want to keep that out of scope for this one. 
I know how to recognize it, but I don't know how to change the menu item.

Another thing is that the message is promising to put the file into the bin.

https://github.com/AuroraEditor/AuroraEditor/blob/4ce4368b8bc5ad0e8fd793258e3dd35ae5d46969/AuroraEditor/Core/NavigatorSidebar/Model/ProjectNavigator/ProjectNavigatorMenu.swift#L271-L272

And we should respect that.

**Comment by nanashili** [comment]
> > Maybe give the user an option? Delete permanently or move to trash?
> 
> 
> 
> This is what Xcode does as well, and might be the safest option.
> 
> 
> 
> We can make ⌘ Delete for permanent delete, but I want to keep that out of scope for this one. 
> 
> I know how to recognize it, but I don't know how to change the menu item.
> 
> 
> 
> Another thing is that the message is promising to put the file into the bin.
> 
> 
> 
> https://github.com/AuroraEditor/AuroraEditor/blob/4ce4368b8bc5ad0e8fd793258e3dd35ae5d46969/AuroraEditor/Core/NavigatorSidebar/Model/ProjectNavigator/ProjectNavigatorMenu.swift#L271-L272
> 
> 
> 
> And we should respect that.

Makes sense, but definitely something we should add in the future.

**Review by nanashili — APPROVED** [review]

**Comment by aurora-care-bear** [comment]
Hey @0xWDG,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Pull request merged**
