### PR TITLE
Replace Logging system with `os_log`/`Logger()`

### PR DESCRIPTION
**Pull request by 0xWDG**
## Summary

Replace Logging system with `os_log`/`Logger()`

## Changes Made

Changed all `Log.info()`, `Log.warning()`, `Log.error()`, `Log.xxx`

## TODO

None

## Motivation

OS_Log / Logger, has built in support for privacy redacting, and supports right click and go to line

## Testing

N/A

## Screenshots/GIFs

N/A

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [x] Code has been tested and verified.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.
- [x] Reviewed by at least one other contributor.

## Related Issues

This PR addresses the following issue(s): None

## Additional Notes

For `Log.error()` I added a new line with `auroraMessageBox(message)`

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Comment by nanashili** [comment]
Discard this, rather replace the following:
Screenshot 2024-02-22 at 22 16 57


Here is the file: https://github.com/AuroraEditor/AuroraEditor/blob/140d162ef4a0fbd7c0ae48b456e768a9b7be342e/AuroraEditor/Utils/Log/Log.swift#L232

**Comment by 0xWDG** [comment]
> Discard this, rather replace the following: Screenshot 2024-02-22 at 22 16 57
> 
> Here is the file:
> 
> https://github.com/AuroraEditor/AuroraEditor/blob/140d162ef4a0fbd7c0ae48b456e768a9b7be342e/AuroraEditor/Utils/Log/Log.swift#L232

Not possible since the right click go to message will not work.

**Comment by nanashili** [comment]
Well that's not ideal

**Comment by 0xWDG** [comment]
Yup, but luckily not too much work.
60A521D2-7491-442E-AD55-655F63A7740F

**Review by nanashili — APPROVED** [review]
LGTM

**Comment by aurora-care-bear** [comment]
Hey @0xWDG,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Pull request merged**
