### PR TITLE
Bug: Theme issue on launch

### PR DESCRIPTION
**Pull request by jazzlux**
## Summary

Made sure that if system theme is dark, first launch of the editor includes theme aligned with system.

## Changes Made

ThemeModel().loadThemes() can now check what theme is set in system and provide theme colours accordingly.

## Motivation

As I opened the editor for the first time and I use darkmode I was "hit"with white text editor.

## Testing

if in AppPreferencesModel().loadPreferences() filemanager.fileExists(atPath: preferencesURL.path) then i get preferences without theme according to system settings.

## Screenshots/GIFs

after change

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [ ] Code has been tested and verified.
- [ ] Documentation has been updated to reflect the changes.
- [ ] All tests pass successfully.
- [ ] Code follows the project's coding guidelines and style.
- [ ] The branch is up-to-date with the latest changes from the main branch.
- [ ] Reviewed by at least one other contributor.

### CODE REVIEW

**Comment by 0xWDG** [comment]
Hey @jazzlux,

Thanks for your contribution, this fault happens to me too, but your PR does not solve it for me.

image

**Comment by jazzlux** [comment]
> Hey @jazzlux,
> 
> Thanks for your contribution, this fault happens to me too, but your PR does not solve it for me.
> 
> image

Ah interesting ! I’ll investigate

**Comment by 0xWDG** [comment]
> @0xWDG : Why don't you see the line number?

No idea, not looked into it yet, but I see a all white screen, only when selecting (as in screenshot) I see something.

**Comment by nanashili** [comment]
Converting this to draft until ready for re-review.

**Comment by jazzlux** [comment]
> @0xWDG : Why don't you see the line number?

Not sure how this should work normally, are line numbers should be visible at the first launch or is it matter of changing settings ? I'm not sure why line count would not be visible at this moment :(

**Comment by nanashili** [comment]
> > @0xWDG : Why don't you see the line number?
> 
> 
> 
> Not sure how this should work normally, are line numbers should be visible at the first launch or is it matter of changing settings ? I'm not sure why line count would not be visible at this moment :(

That might be editor side and not theme side, don't worry to much about that that right now

**Comment by 0xWDG** [comment]
I'm not able to check it tonight, but since it does not break, and does work for you, i will approve this PR, it will be merged after the tests are completed, thanks for your contribution!

Within a few minutes your name will also be on https://auroraeditor.com/#contributors

**Review by 0xWDG — APPROVED** [review]
LGTM

**Pull request merged**
