### PR TITLE
Revert/add package dot resolved

### PR DESCRIPTION
**Pull request by 0xWDG**
## Summary

Revert/add package dot resolved

## Changes Made

Revert/add package dot resolved

## TODO

Find a way to ensure we keep on version 2 since version 3 is not supported by Xcode 15.0.1.

## Motivation

https://github.com/AuroraEditor/AuroraEditor/pull/702#issuecomment-2239265380

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [x] Code has been tested and verified.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.
- [x] Reviewed by at least one other contributor.

## Related Issues

This PR addresses the following issue(s): https://github.com/AuroraEditor/AuroraEditor/pull/702#issuecomment-2239265380

## Additional Notes

None

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Review by nanashili — APPROVED** [review]

**Comment by aurora-care-bear** [comment]
Hey @0xWDG,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Comment by humblehacker** [comment]
@0xWDG It looks like your TODO will solve itself in two days:
[Default Xcode on macOS 14 Sonoma will be set to Xcode 15.4 on July, 22 #10121](https://github.com/actions/runner-images/issues/10121)

**Comment by 0xWDG** [comment]
> @0xWDG It looks like your TODO will solve itself in two days: [Default Xcode on macOS 14 Sonoma will be set to Xcode 15.4 on July, 22 #10121](https://github.com/actions/runner-images/issues/10121)

I updated the runner yesterday to Xcode 15.3 and macos-14, we used macos 13, since we do major release - 1 version.

**Comment by humblehacker** [comment]
Ah, didn't realize that. Thanks!

**Pull request merged**
