### PR TITLE
Clean development team action

### PR DESCRIPTION
**Pull request by 0xWDG**
Clean development team action

## Summary

Clean development team action

## Changes Made

Added clean development team action

## TODO

None

## Motivation

development team should be empty on the main repo (development)

## Testing

N/A
## Screenshots/GIFs

N/A
## Checklist

Please ensure all of the following are completed before submitting the PR:

- [x] Code has been tested and verified.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.
- [x] Reviewed by at least one other contributor.

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Comment by nanashili** [comment]
Maybe not on push? Maybe when a PR is created?

**Comment by 0xWDG** [comment]
> Maybe not on push? Maybe when a PR is created?

Can we write to someone else's repo, probably we can, but how can we extract this for AE Bot? (last push command)

**Review by nanashili — DISMISSED** [review]

**Comment by 0xWDG** [comment]
@aurora-care-bear please approve

**Review by aurora-care-bear — APPROVED** [review]
Approved on behalf of @0xWDG

**Comment by aurora-care-bear** [comment]
Hey @0xWDG,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Pull request merged**
