### PR TITLE
Fix: Editor is always in dark mode

### PR DESCRIPTION
**Pull request by boscojwho**
## Summary
Fixes issue #693 

## Changes Made
- Fix issue where `CodeEditorViewWrapper` did not adapt to system appearance.
- Add missing properties from `EditorTheme` to `AuroraTheme.EditorColors`. 
- Update theme loaders with default attrs (values taken from existing Aurora theme).

## Testing
Verified that theme does adapt to selected system appearance (even if user explicitly selects a light theme, makes sense since all other UI elements currently adapt to system appearance anyway).

## Screenshots/GIFs

https://github.com/user-attachments/assets/3470fd44-d734-4c15-9aeb-46c298b266f5

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [x] Code has been tested and verified.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.
- [x] Reviewed by at least one other contributor.

## Related Issues
#693

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Comment by 0xWDG** [comment]
Nice PR, it seems like you have some linting issues, can you fix that please?

**Comment by nanashili** [comment]
@0xWDG I wonder if we shouldn't just go the way of only light or dark mode themes and remove universal in general..... Because currently there are 3 categories for themes but I think 2 categories light and dark makes more sense.

**Comment by 0xWDG** [comment]
> @0xWDG I wonder if we shouldn't just go the way of only light or dark mode themes and remove universal in general..... Because currently there are 3 categories for themes but I think 2 categories light and dark makes more sense.

We should support a auto (and that should be the default), not everyone uses or light or dark mode, i run a program on my mac which switches the system appearance according to the lightsensor of my mac.

**Comment by nanashili** [comment]
> > @0xWDG I wonder if we shouldn't just go the way of only light or dark mode themes and remove universal in general..... Because currently there are 3 categories for themes but I think 2 categories light and dark makes more sense.
> 
> We should support a auto (and that should be the default), not everyone uses or light or dark mode, i run a program on my mac which switches the system appearance according to the lightsensor of my mac.

I'm not talking about that, auto is system wide we don't have to implement it as long as we use the `colorScheme` variable.... I'm talking about the universal tab in settings for themes

**Comment by 0xWDG** [comment]
> > > @0xWDG I wonder if we shouldn't just go the way of only light or dark mode themes and remove universal in general..... Because currently there are 3 categories for themes but I think 2 categories light and dark makes more sense.
> 
> > 
> 
> > We should support a auto (and that should be the default), not everyone uses or light or dark mode, i run a program on my mac which switches the system appearance according to the lightsensor of my mac.
> 
> 
> 
> I'm not talking about that, auto is system wide we don't have to implement it as long as we use the `colorScheme` variable.... I'm talking about the universal tab in settings for themes

Agreed, but we need to revamp the whole theme thing...
But yes, we can remove the universal.

**Comment by 0xWDG** [comment]
> > > @0xWDG I wonder if we shouldn't just go the way of only light or dark mode themes and remove universal in general..... Because currently there are 3 categories for themes but I think 2 categories light and dark makes more sense.
> 
> > 
> 
> > We should support a auto (and that should be the default), not everyone uses or light or dark mode, i run a program on my mac which switches the system appearance according to the lightsensor of my mac.
> 
> 
> 
> I'm not talking about that, auto is system wide we don't have to implement it as long as we use the `colorScheme` variable.... I'm talking about the universal tab in settings for themes

One side note, `colorScheme` is not reliable on initialization of a view.

**Comment by boscojwho** [comment]
> > @0xWDG I wonder if we shouldn't just go the way of only light or dark mode themes and remove universal in general..... Because currently there are 3 categories for themes but I think 2 categories light and dark makes more sense.
> 
> We should support a auto (and that should be the default), not everyone uses or light or dark mode, i run a program on my mac which switches the system appearance according to the lightsensor of my mac.

I agree: Modern apps should have a top-level option to "use system appearance", "always dark", or "always light" (just like in System Settings).

Related: 
- I think the light/dark themes should be packaged as variants of a theme (e.g. I had to write a function in `ThemeModel` to convert a light theme to its dark theme counterpart, when ideally, a theme should just know what variants it provides). 
- Having themes contain variants means we could also add variants like "neutral", "accessibility" or "dyslexic" to a particular theme/design system.
- To use macOS's system settings as an example, there's the system color schemes "dark" and "light", and there's accent colors like "purple" or "orange", and depending on the color scheme, the accent colors will adapt accordingly.  Here, accent colors are the "theme/design system", so to speak.

**Comment by boscojwho** [comment]
> > > > @0xWDG I wonder if we shouldn't just go the way of only light or dark mode themes and remove universal in general..... Because currently there are 3 categories for themes but I think 2 categories light and dark makes more sense.
> > 
> > 
> > > 
> > 
> > 
> > > We should support a auto (and that should be the default), not everyone uses or light or dark mode, i run a program on my mac which switches the system appearance according to the lightsensor of my mac.
> > 
> > 
> > I'm not talking about that, auto is system wide we don't have to implement it as long as we use the `colorScheme` variable.... I'm talking about the universal tab in settings for themes
> 
> One side note, `colorScheme` is not reliable on initialization of a view.

Interesting, is this something happening in Aurora or have you seen this behaviour elsewhere? I don't recall having experienced this in the past.

**Comment by 0xWDG** [comment]
> > > > > @0xWDG I wonder if we shouldn't just go the way of only light or dark mode themes and remove universal in general..... Because currently there are 3 categories for themes but I think 2 categories light and dark makes more sense.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > We should support a auto (and that should be the default), not everyone uses or light or dark mode, i run a program on my mac which switches the system appearance according to the lightsensor of my mac.
> 
> > > 
> 
> > > 
> 
> > > I'm not talking about that, auto is system wide we don't have to implement it as long as we use the `colorScheme` variable.... I'm talking about the universal tab in settings for themes
> 
> > 
> 
> > One side note, `colorScheme` is not reliable on initialization of a view.
> 
> 
> 
> Interesting, is this something happening in Aurora or have you seen this behaviour elsewhere? I don't recall having experienced this in the past.

On iOS the parameters will be updated after initialization, I used it for setting a specific background to a view (Gradient), and I always saw after initialization of the view that the background of the screen changed to the correct color.

**Comment by 0xWDG** [comment]
> > > @0xWDG I wonder if we shouldn't just go the way of only light or dark mode themes and remove universal in general..... Because currently there are 3 categories for themes but I think 2 categories light and dark makes more sense.
> 
> > 
> 
> > We should support a auto (and that should be the default), not everyone uses or light or dark mode, i run a program on my mac which switches the system appearance according to the lightsensor of my mac.
> 
> 
> 
> I agree: Modern apps should have a top-level option to "use system appearance", "always dark", or "always light" (just like in System Settings).
> 
> 
> 
> Related: 
> 
> - I think the light/dark themes should be packaged as variants of a theme (e.g. I had to write a function in `ThemeModel` to convert a light theme to its dark theme counterpart, when ideally, a theme should just know what variants it provides). 
> 
> - Having themes contain variants means we could also add variants like "neutral", "accessibility" or "dyslexic" to a particular theme/design system.
> 
> - To use macOS's system settings as an example, there's the system color schemes "dark" and "light", and there's accent colors like "purple" or "orange", and depending on the color scheme, the accent colors will adapt accordingly.  Here, accent colors are the "theme/design system", so to speak.

1. Yes we can
2. I agree we need more variation options
3. We do use the accent color for (custom) elements

Our biggest issue right now is that we support 3 different systems for theming.
- using a json file in "Aurora editor format";
- using a TextMate theme;
- using a Visual Studio Code theme;

This is not ideal because it is made too complicated to maintain.

In a ideal world we make one theme definition (struct or protocol). 
Then we can subclass that for example to get the vs code theme into the theme definition.

**Comment by boscojwho** [comment]
@0xWDG @nanashili You guys are probably more familiar with why Periphery might be failing here, there's a lot of noise in that failure log, and I don't see it saying specifically what it's failing on. Help greatly appreciated =)

**Comment by nanashili** [comment]
> @0xWDG @nanashili You guys are probably more familiar with why Periphery might be failing here, there's a lot of noise in that failure log, and I don't see it saying specifically what it's failing on. Help greatly appreciated =)

It's mostly for unused code, that it's complaining about. It's not required to pass so don't stress to much. Also I'll review your PR in 5 mins.

**Comment by nanashili** [comment]
Screenshot 2024-07-25 at 10 15 34
Not going to lie, I think I prefer light mode lol

**Review by nanashili — APPROVED** [review]
LGTM

**Comment by aurora-care-bear** [comment]
Hey @boscojwho,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Comment by 0xWDG** [comment]
Thanks for testing @nanashili

**Pull request merged**
