### PR TITLE
UI: Fixed Commit History Popover Layout

### PR DESCRIPTION
**Pull request by nanashili**
## Summary

The following pull request fixes the bug presented in #720 video...

## Changes Made

Fixed the layout bug in the popover presented by the avatar

## TODO

N/A

## Motivation

N/A

## Testing

N/A

## Screenshots/GIFs
Screenshot 2024-07-14 at 00 16 56

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [x] Code has been tested and verified.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.
- [x] Reviewed by at least one other contributor.

## Related Issues

This PR addresses the following issue(s): N/A

## Additional Notes

N/A

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Review by 0xWDG — APPROVED** [review]

**Comment by 0xWDG** [comment]
@aurora-care-bear please approve this pr

**Review by aurora-care-bear — APPROVED** [review]
Approved on behalf of @0xWDG

**Comment by aurora-care-bear** [comment]
Hey @nanashili,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Pull request merged**
