### PR TITLE
About view changes

### PR DESCRIPTION
**Pull request by 0xWDG**
# Description

- Make About view nicer
- Put preferences location back in preferences pane (General)
- Added an function to open the about view
- Added AE Oniguruma package.
- Grouped General preferences
- Grouped Source control preferences

# Related Issue

* N/A

# Checklist

- [x] My changes generate no new warnings
- [x] My code builds and runs on my machine
- [x] I documented my code

# Screenshots

### Re added preferences location:
image

### About view:
image

### More grouping of general preferences:
image

### More grouping of source control preferences:
image

### CODE REVIEW

**Comment by nanashili** [comment]
I removed it out of preferences for a reason

**Comment by 0xWDG** [comment]
> I removed it out of preferences for a reason

I think this one line in settings looks way better then what is currently in the about window.

**Comment by nanashili** [comment]
> > I removed it out of preferences for a reason
> 
> 
> 
> I think this one line in settings looks way better then what is currently in the about window.

Then you might just as well add location panel back because it will get removed once i redo settings

**Comment by nanashili** [comment]
Also don't just group things together, i had it set like that because then the list doesn't look so big... because now with the grouping you made it feels overwhelming and not very clean

**Review by nanashili — APPROVED** [review]

**Comment by 0xWDG** [comment]
> Also don't just group things together, i had it set like that because then the list doesn't look so big... because now with the grouping you made it feel overwhelming and not very clean

Build it, it looks way better then separate group boxes with one item in it.

**Pull request merged**
