### PR TITLE
Migration: Migrated old version control code to the new version control code

### PR DESCRIPTION
**Pull request by nanashili**
## Summary
Migrated old version control code to the new version control code

## Changes Made
Migrated old version control code to the new version control code

## TODO
None

## Motivation
The new version of version control required AE to be updated

## Testing
None

## Screenshots/GIFs
None

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [x] Code has been tested and verified.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.

## Related Issues

This PR addresses the following issue(s): None

## Additional Notes
None

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Review by 0xWDG — APPROVED** [review]

**Comment by 0xWDG** [comment]
@aurora-care-bear please approve

**Review by aurora-care-bear — APPROVED** [review]
Approved on behalf of @0xWDG

**Comment by aurora-care-bear** [comment]
Hey @nanashili,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Pull request merged**
