### PR TITLE
Sync beta to main

### PR DESCRIPTION
**Pull request by 0xWDG**
Sync beta to main

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Comment by 0xWDG** [comment]
@aurora-care-bear please approve this PR.

**Review by aurora-care-bear — APPROVED** [review]
Approved on behalf of @0xWDG

**Review by nanashili — APPROVED** [review]

**Comment by aurora-care-bear** [comment]
Hey @0xWDG,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Pull request merged**
