### PR TITLE
Feature: Add Support for Floatable Status Bar Content

### PR DESCRIPTION
**Pull request by nanashili**
## Summary

This PR adds support for making the status bar content floatable.

## Changes Made

- Added settings for enabling/disabling the floating view.
- Added a timeout option for when floating is enabled.

## TODO

N/A

## Motivation

The primary goal is to achieve a cleaner design.

## Testing

- Tested enabling and disabling the floating view.
- Tested the visibility timeout when floating is enabled.

## Screenshots/GIFs

Screenshot 2024-08-01 at 8 59 12 PM

image

https://github.com/user-attachments/assets/8d2e30b0-0804-47fd-83e2-f1a915762f4a

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [x] Code has been tested and verified.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.
- [x] Reviewed by at least one other contributor.

## Related Issues

This PR addresses the following issue(s): N/A

## Additional Notes

N/A

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Comment by 0xWDG** [comment]
If no auto hide is set, it does not show never, you need to select it before you see never.

3945CC15-4AFF-452F-9A47-602157CD9988_4_5005_c

**Comment by 0xWDG** [comment]
~Moving `Text("Never").tag(0)` to the first entry on the picker seems to resolve the issue for me.~
It looks like a database issue, when you have old preferences it will generate a white field, so it will fix itself for new users, and since we dont have a lot of existing users, I'm fine with this.

**Review by 0xWDG — APPROVED** [review]

**Comment by aurora-care-bear** [comment]
Hey @nanashili,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Pull request merged**
