### PR TITLE
Enable Concurrency checks

### PR DESCRIPTION
**Pull request by 0xWDG**
## Summary

Enable Concurrency checks

> [!IMPORTANT]
> This PR introduces a lot of warnings, since concurrency checking is turned on.

From 900+ warnings to 692.

## Changes Made

Made some things concurrency safe.

## TODO

Make more things concurrency safe.

## Motivation

We need to change to concurrency at some point

## Testing

Tests will pass.

## Screenshots/GIFs

None.

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [x] Code has been tested and verified.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.
- [x] Reviewed by at least one other contributor.

## Issue:
Issue: #774

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Review by nanashili — APPROVED** [review]
LGTM, we just need to be careful with adding `@MainActor` everywhere

**Comment by aurora-care-bear** [comment]
Hey @0xWDG,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Comment by 0xWDG** [comment]
> LGTM, we just need to be careful with adding `@MainActor` everywhere

Yup, but @Observable and Views must run on the @MainActor so that's why I added them 😊

**Pull request merged**
