### PR TITLE
Modified README.md file

### PR DESCRIPTION
**Pull request by ayushi-ras**
## Summary

Modified README.md file

## Changes Made

Added how to install section

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [ ] Code has been tested and verified.
- [x] Documentation has been updated to reflect the changes.
- [ ] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.
- [ ] Reviewed by at least one other contributor.

### CODE REVIEW

**Comment by nanashili** [comment]
Hi @ayushi-ras, does `elementary OS` actually support MacOS apps?

**Comment by ayushi-ras** [comment]
> Hi @ayushi-ras, does `elementary OS` actually support MacOS apps?

Elementary OS isn't same as macOS desktop.

However EOS practices a quite similar user experience and user interfacing guidelines and they got a whole manifesto on these user interaction related work flows. And every desktop environment like Gnome, KDE, etc has it's own rule set when its comes to visual and user experience.

**Comment by 0xWDG** [comment]
> > Hi @ayushi-ras, does `elementary OS` actually support MacOS apps?
> 
> Elementary OS isn't same as macOS desktop.
> 
> However EOS practices a quite similar user experience and user interfacing guidelines and they got a whole manifesto on these user interaction related work flows. And every desktop environment like Gnome, KDE, etc has it's own rule set when its comes to visual and user experience.

We understand that, but can it run Aurora Editor?
If it compiles and runs this section is ok, otherwise we don't want to add this section.

can you otherwise please provide screenshots of Aurora Editor running on Elementary OS?

**Comment by ayushi-ras** [comment]
Hey

Check out this link
https://snapcraft.io/install/aurora-editor/elementary

It can run on it

**Comment by 0xWDG** [comment]
That is a different product with the same name ☹️

https://github.com/aguang-xyz/aurora-editor

Our product does not run on Linux, maybe in the future, when we can find a cross compatible SwiftUI like engine, but for now it doesn't.

thanks for your PR, but I close it since this Aurora Editor does not support anything else than MacOS at this moment.

**Pull request closed without merging**
