### PR TITLE
[Clean] Remove package.resolved

### PR DESCRIPTION
**Pull request by 0xWDG**
## Summary

Remove package.resolved

## Changes Made

Package.resolved should not be tracked.
See: https://forums.swift.org/t/package-resolved-should-go-in-the-gitignore/14699

## TODO

None.

## Motivation

https://forums.swift.org/t/package-resolved-should-go-in-the-gitignore/14699

## Testing

None.

## Screenshots/GIFs

None.

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [x] Code has been tested and verified.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.
- [x] Reviewed by at least one other contributor.

## Related Issues

None.

## Additional Notes

None.

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Review by nanashili — DISMISSED** [review]

**Comment by 0xWDG** [comment]
@aurora-care-bear please approve

**Review by aurora-care-bear — APPROVED** [review]
Approved on behalf of @0xWDG

**Comment by aurora-care-bear** [comment]
Hey @0xWDG,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Comment by humblehacker** [comment]
@0xWDG Would you consider reverting this change? 

Package.resolved is necessary for reproducible builds, especially considering that this project has a large number of dependencies pointing to branches and not versions. Without Package.resolved, it's unlikely a newcomer (such as myself) can successfully build the project, because the specific commits for each of the dependencies used by whoever committed last is unknown to the newcomer.

I came to Aurora after seeing a post on Mastodon. I installed and attempted to open my current project directory. The application crashed. Rather than just open a bug report, I thought I'd at least clone the repo to spin it up in the debugger and see what I could discover. But the project doesn't build cleanly. This is a high entry barrier for newcomers. Please reconsider? 🙏

**Comment by 0xWDG** [comment]
> @0xWDG Would you consider reverting this change?
> 
> Package.resolved is necessary for reproducible builds, especially considering that this project has a large number of dependencies pointing to branches and not versions. Without Package.resolved, it's unlikely a newcomer (such as myself) can successfully build the project, because the specific commits for each of the dependencies used by whoever committed last is unknown to the newcomer.
> 
> I came to Aurora after seeing a post on Mastodon. I installed and attempted to open my current project directory. The application crashed. Rather than just open a bug report, I thought I'd at least clone the repo to spin it up in the debugger and see what I could discover. But the project doesn't build cleanly. This is a high entry barrier for newcomers. Please reconsider? 🙏

Hello, the crash happened because I had updated a package/requirement earlier this morning, I've pushed a fix.

I'm going to pin this version to the editor, this should prevent this in the future.
We did not pin any package, we are pinning packages now to a version.

We had some problems when we used Package.resolved that's why we deleted it.

Thanks.

**Comment by humblehacker** [comment]
Thanks for your changes. It does build for me now. Though I still think you should reconsider. Reproducible builds are important. Without Package.resolved, it will be difficult to reproduce a previously released build because you won't know and will have to guess which commit was used in your dependencies when it was last built. GRDB, for example, is pointing at the master branch. If you have a bug in the previous release, how will you know what GRDB commit it was built with? And if you're working with someone else to track down an issue, but you're each using slightly different versions of your dependencies, you can run into issues like "odd, it works on my machine. Why is it breaking on yours?". Automated tests if you have them could pass today and break tomorrow even if this project has had no commits. I could go on. 

I appreciate you taking the time to consider this suggestion. While I believe it could be beneficial, I understand if it doesn't work for you. Ultimately, it’s your project, and I trust you’ll make the best decision for it. Looking forward to seeing how it evolves!

**Comment by 0xWDG** [comment]
@nanashili Do you think we should remove `Package.resolved` from gitignore?

**Comment by humblehacker** [comment]
One final comment: The forum post you referenced as motivation actually has a strong consensus that Package.resolved should not be included in .gitignore. The discussion highlights the importance of checking it in to ensure reproducible builds and consistent dependency management. The original poster also acknowledged this point in the end.  

But again I defer to your judgement.

**Comment by nanashili** [comment]
I agree with @humblehacker here.

@0xWDG

**Comment by 0xWDG** [comment]
I'm okay with that, but, I we cannot allow (`./Aurora Editor.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved`) changed to version 3 since it causes GitHub Actions to fail, so it requires a manual change.

GitHub Actions runs _Xcode 15.0.1_ and I have no idea since when version 3 is introduced.

```json
{
  "originHash" : "8b568878740ef6d35c6ecc7d2fc0c12cc3a802b1cf96176dfa756f68a33af0ac",
  "pins" : [
    {
      "identity" : "aeextensionkit",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/AuroraEditor/AEExtensionKit.git",
      "state" : {
        "revision" : "65a24d417d018c5840cb354a6290a014b2e82b27",
        "version" : "1.0.1"
      }
    },
    .....
  ],
  "version" : 2, {"COMMENT": "<- This part."}
}
```

**Comment by humblehacker** [comment]
@0xWDG You can choose a newer version of Xcode in your Actions configuration. Package.resolved version 3 started with Xcode 15.3.

**Comment by 0xWDG** [comment]
We try to support current stable version - the last year's stable version.
Unfortunately macOS Sequoia is not yet out, so we then cut of a group of people.
According to https://en.wikipedia.org/wiki/MacOS_version_history we phase out (development) support for macOS 13.5 and only support macOS 14+

@nanashili What do you think?

**Comment by nanashili** [comment]
https://github.com/apollographql/apollo-ios/issues/3355

Based on this issue it seems like it's more the swift version that gets updated not the system it supports. I could be wrong

**Pull request merged**
