### PR TITLE
Fix tabbar, fixes #776

### LINKED ISSUE #776: Tabs are broken on macOS 15+
### Description

image

### To Reproduce

Open anything

### Expected behavior

Open file

### Version information

Aurora Editor: 1.0 (1)
Commit: 38f2847c0d7eadf6278d5a18149a9b00f0df272c
MacOS: 15.1 (24B83)
Xcode: 16.1 (16B40)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 0xWDG**
Fix tabbar, fixes #776

⚠️ Emergency fix.

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Comment by 0xWDG** [comment]
@aurora-care-bear please approve

**Review by aurora-care-bear — DISMISSED** [review]
Approved on behalf of @0xWDG

**Comment by 0xWDG** [comment]
@aurora-care-bear please approve

**Review by aurora-care-bear — DISMISSED** [review]
Approved on behalf of @0xWDG

**Comment by aurora-care-bear** [comment]
Hey @0xWDG,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Pull request merged**
