### PR TITLE
zh_Hant loc

### PR DESCRIPTION
**Pull request by shuang886**
## Summary

Provide traditional Chinese translations for strings

## Changes Made

Provide traditional Chinese translations for strings

## TODO

Looks like most strings in this app have not yet been added to the localization strings files.

Better yet, you should really consider using the new string catalogs (https://developer.apple.com/documentation/xcode/localizing-and-varying-text-with-a-string-catalog) instead.

## Motivation

Traditional Chinese support

## Testing

Light testing around the app

## Screenshots/GIFs

截圖 2024-01-27 下午1 08 48

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [X] Code has been tested and verified.
- [ ] Documentation has been updated to reflect the changes.
- [ ] All tests pass successfully.
- [X] Code follows the project's coding guidelines and style.
- [X] The branch is up-to-date with the latest changes from the main branch.
- [ ] Reviewed by at least one other contributor.

## Related Issues

This PR partly addresses the following issue(s): https://github.com/AuroraEditor/AuroraEditor/issues/392

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Comment by 0xWDG** [comment]
Looks good, if you want to help to set up the string catalog, you are more than welcome.

thanks for this PR.

**Review by 0xWDG — APPROVED** [review]
LGTM

**Comment by aurora-care-bear** [comment]
Hey @shuang886,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Pull request merged**
