### PR TITLE
Replace custom SwiftLint rules with built-in rules

### PR DESCRIPTION
**Pull request by SimplyDanny**
The two removed rules are actually enabled by default as built-in rules in SwiftLint. I made them report errors to match the behavior of the custom rules.

The custom rule `swiftlint_file_disabling` would be another candidate as SwiftLint comes with the similar rule `blanket_disable_command`. The only difference is that it allows `swiftlint:disable` commands if they are follwed by another `swiftlint:enable`.

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Review by nanashili — APPROVED** [review]

**Comment by nanashili** [comment]
LGTM

**Review by 0xWDG — APPROVED** [review]
Thanks!

**Comment by aurora-care-bear** [comment]
Hey @SimplyDanny,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Pull request merged**
