### PR TITLE
Improve accessibility

### PR DESCRIPTION
**Pull request by 0xWDG**
## Summary

Enable more SwiftLint Rules

## Changes Made

Enabled more rules, and fixed those errors.

```swift

Text("Test") // as "button"
    .onTap { /* do something */ }
    .accessibilityAddTraits(.isButton)

Text("Test") // as "link"
    .onTap { /* do something */ }
    .accessibilityAddTraits(.isLink)

Image("star") // With accessibility label
    .accessibilityLabel(Text("GitHub"))

Image("Star") // Accessibility label not needed
    .accessibilityHidden(true)
```

## TODO

N/A

## Motivation

Better support for accessibility

## Testing

None

## Screenshots/GIFs

None

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [x] Code has been tested and verified.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.
- [x] Reviewed by at least one other contributor.

## Related Issues

None

## Additional Notes

None

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Comment by 0xWDG** [comment]
Start: Done linting! Found 128 violations, 128 serious in 506 files.

**Review by nanashili — APPROVED** [review]
LGTM

**Comment by aurora-care-bear** [comment]
Hey @0xWDG,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Pull request merged**
