### PR TITLE
Users can now delete git branches

### PR DESCRIPTION
**Pull request by nanashili**
# Description
Users can now delete branches in the repository view by right clicking on a selected branch.

Users are not allowed to delete their currently used branch. As pre-caution we disable the delete function if the current projects selected git repo is that of the selected branch from the repository view.

# Related Issue

* NONE

# Checklist

- [X] I read and understood the [contributing guide](https://github.com/AuroraEditor/AuroraEditor/blob/main/CONTRIBUTING.md) as well as the [code of conduct](https://github.com/AuroraEditor/AuroraEditor/blob/main/CODE_OF_CONDUCT.md)
- [X] My changes generate no new warnings
- [X] My code builds and runs on my machine
- [X] I documented my code
- [X] Review requested

# Screenshots

### CODE REVIEW

**Review by wdg — APPROVED** [review]

**Comment by KaiTheRedNinja** [comment]
image

For some reason the toolbar thing acts weirdly without a git repo. I don't think that this is something caused by your PR but since you're working in the area of branches here it might be good to fix this.

**Comment by KaiTheRedNinja** [comment]
image

When i git init in a folder there's this error. Might be related to the git client not updating the current branch.

**Comment by nanashili** [comment]
> image
> 
> For some reason the toolbar thing acts weirdly without a git repo. I don't think that this is something caused by your PR but since you're working in the area of branches here it might be good to fix this.

Should be a next pr instead

**Comment by nanashili** [comment]
> image
> 
> When i git init in a folder there's this error. Might be related to the git client not updating the current branch. If i restart AE and go to the repositories navigator the same thing happens.

Yes because your trying to index github branches when there is none. We should do state management on the repos also. A next pr

**Review by KaiTheRedNinja — APPROVED** [review]

**Pull request merged**
