### PR TITLE
Fix last line issues

### PR DESCRIPTION
**Pull request by KaiTheRedNinja**
# Description

Fixes several issues related to the last line in the editor

# Related Issue

* #305 
* #297 

# Checklist

- [x] When last line is deleted, don't crash
  - [x] When the second last line is empty
  - [x] When the second last line has content
- [x] Update the gutter view properly when last line deleted

- [x] I read and understood the [contributing guide](https://github.com/AuroraEditor/AuroraEditor/blob/main/CONTRIBUTING.md) as well as the [code of conduct](https://github.com/AuroraEditor/AuroraEditor/blob/main/CODE_OF_CONDUCT.md)
- [x] My changes generate no new warnings
- [x] My code builds and runs on my machine
- [x] I documented my code
- [x] Review requested

# Screenshots

https://user-images.githubusercontent.com/88234730/198183951-42ea2b9a-79d7-40fd-bfe5-66cb7cb7feda.mov

For context: deleting a ton of empty lines at the end of a file or opening an empty file sometimes crashed the editor. Now, it does not.

### CODE REVIEW

**Comment by KaiTheRedNinja** [comment]
Known issues:
- Typing has an odd effect on the gutter view numbers past the insertion point
- Deleting the last line hides the number at the insertion point

I'll work on these bugs, but this PR is feature complete and can be merged.

**Comment by nanashili** [comment]
## Issues
* The gutter view disappears in highlighted files.
* Creates a new line when removing text on last line.
* Last line doesn't always get removed when deleting it.

Putting PR in draft till further notice.

**Comment by KaiTheRedNinja** [comment]
Bit more information on the issues nanashili raised:
- Gutter view disappears when you spam newline
- Can't reproduce this, however I think I'll just add this as a feature where there's always a trailing blank line. Its how xcode does it anyway.
- Can't reproduce this either

Plus I have discovered a new bug. 

In the `applyTheme` function, line 86, appears to have an occasional `Thread 1: "NSMutableRLEArray replaceObjectsInRange:withObject:length:: Out of bounds"` error in highlighted files. 

`Thread 1: "-[AuroraEditor.CodeLayoutManager _fillLayoutHoleForCharacterRange:desiredNumberOfLines:isSoft:] *** attempted layout while textStorage is editing.  It is not valid to cause the layoutManager to do layout while the textStorage is editing (ie the textStorage has been sent a beginEditing message without a matching endEditing.)"` also appears to be thrown by AppDelegate. I think this is due to me reordering certain functions.

**Comment by KaiTheRedNinja** [comment]
Closing due to crashes on highlighting files. Will open another PR when I have a working version.

**Pull request closed without merging**
