### PR TITLE
Fixed #124

### LINKED ISSUE #124: When last tab is closed `⌘W` should close the window
### Description

When last tab is closed `⌘W` should close the window

### To Reproduce

Press ⌘W when all tabs are closed

### Expected behavior

Closing window

### Version information

Aurora Editor: 1.0 (1)
Commit: 1a7a85ae90578c92c7cb06a3c271d4cd55a68b07
MacOS: 13.0 (22A5321d)
Xcode: 14.0 (14A5270f)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AlexBurneikis**

### CODE REVIEW

**Comment by KaiTheRedNinja** [comment]
BTW next time add a small description for the PR contents.

Gonna check
- [ ] That the button doesn't show up
- [ ] That the shortcut closes the window
- [ ] The shortcut doesn't trigger when theres tabs open
- [ ] That it only closes the window selected when multiple windows are open
- [ ] That it closes the window when other elements in the window are focused (eg. the nav sidebar)

**Comment by KaiTheRedNinja** [comment]
The button doesn't show up, however I can't seem to close the window with cmd-w.

**Comment by AlexBurneikis** [comment]
Strange, I'll have another look at it.

**Comment by AlexBurneikis** [comment]
Alrighty, that commit should hopefully fix it so that it works more better...

Im gunna check if it works out of focus.

**Comment by KaiTheRedNinja** [comment]
Hows it going so far? do you want a code review yet?

also consider joining the discord, the link is in the readme. most of the development discussion happens over there.

**Review by wdg — APPROVED** [review]

**Comment by nanashili** [comment]
Works fine my side, merging.

**Review by nanashili — APPROVED** [review]

**Comment by nanashili** [comment]
@all-contributors please add @AlexBurneikis  for Bug reports

**Pull request merged**
